import pandas as pd
import numpy as np


def drop_sparse_columns(df, threshold=70):
    
    
    # essential columns we never drop
    keep_always = ['country', 'year', 'iso_code']
    
    # calculate missing percentage for each column
    missing_pct = (df.isnull().sum() / len(df) * 100)
    #find columns exceeding threshold
    cols_to_drop = missing_pct[missing_pct > threshold].index.tolist()
    
    # dont drop the essential columns even if sparse
    cols_to_drop = [col for col in cols_to_drop if col not in keep_always]
    
    # drop the columns and report
    before_cols = len(df.columns)
    df = df.drop(columns=cols_to_drop)
    after_cols = len(df.columns)
    
    print(f"dropped {before_cols - after_cols} sparse columns (>{threshold}% missing)")
    return df


#keeping only recent complete data from 2000 onwards
def filter_modern_data(df, min_year=2000):
    
    # count rows before filtering
    before = len(df)
    df = df[df['year'] >= min_year] # keep only yearrs >= min_year
    removed = before - len(df) # report how many rows removed
    
    print(f"filtered to {min_year}+: removed {removed:,} rows")
    return df


def remove_duplicates(df):
    """Remove exact duplicate rows."""
    dupes = df.duplicated().sum() #count dupes
    if dupes > 0: #remove dupes, keeping first occurence
        df = df.drop_duplicates().reset_index(drop=True)
        print(f"removed {dupes} duplicate rows")
    return df


def handle_missing(df):
    
    # define which columns are essential lfor analysis
    key_cols = ['electricity_generation', 'fossil_fuel_consumption', 'renewables_electricity']
    key_cols = [col for col in key_cols if col in df.columns] #check which key columns actually exist in the dataset
    
    if not key_cols:
        print("warning: No key energy columns found, skipping missing value filter")
        return df
    
    before = len(df) # count rows before filtering
    df = df.dropna(subset=key_cols, how='any') # drop any row missing any of these key columns
    removed = before - len(df) # report how many rows were removed
    
    if removed > 0:
        print(f"removed {removed:,} rows missing key energy columns")
    return df


def engineer_features(df):
    
    
   
    if 'renewables_electricity' in df.columns and 'electricity_generation' in df.columns:
        df['renewable_elec_share'] = (df['renewables_electricity'] / df['electricity_generation'] * 100).round(2)
    
    #second feature is fossil vs renewable consumption compariosn
    # using +1 in denominator prevents division by zero
    if 'fossil_fuel_consumption' in df.columns and 'renewables_consumption' in df.columns:
        df['fossil_renewable_ratio'] = (df['fossil_fuel_consumption'] / (df['renewables_consumption'] + 1)).round(2)
    
    # third feature is coal's share of electricity generation
    if 'coal_electricity' in df.columns and 'electricity_generation' in df.columns:
        df['coal_elec_share'] = (df['coal_electricity'] / df['electricity_generation'] * 100).round(2)
    
   
    if 'nuclear_electricity' in df.columns and 'electricity_generation' in df.columns:
        df['nuclear_elec_share'] = (df['nuclear_electricity'] / df['electricity_generation'] * 100).round(2)
    
    print("created features: renewable_elec_share, fossil_renewable_ratio, coal_elec_share, nuclear_elec_share")
    return df


def select_key_columns(df):
    
    # always keep these identifiers
    keep = ['country', 'year', 'iso_code', 'population', 'gdp']
    
    #primary key metrics
    primary = ['electricity_generation', 'primary_energy_consumption']
    
   
    sources = [
        'fossil_fuel_consumption', 'coal_consumption', 'gas_consumption', 'oil_consumption',
        'renewables_consumption', 'solar_consumption', 'wind_consumption', 'hydro_consumption',
        'nuclear_consumption', 'biofuel_consumption'
    ]
    
    #electricity generated by source
    electricity = [
        'fossil_electricity', 'coal_electricity', 'gas_electricity', 'oil_electricity',
        'renewables_electricity', 'solar_electricity', 'wind_electricity', 'hydro_electricity',
        'nuclear_electricity', 'biofuel_electricity'
    ]
    
    # per capita version of metricles 
    per_capita = [col for col in df.columns if 'per_capita' in col]
    
   
    engineered = [col for col in df.columns if col.startswith(('renewable_', 'fossil_', 'coal_', 'nuclear_'))]
    # combine all lists
    cols_to_keep = list(set(keep + primary + sources + electricity + per_capita + engineered))
    #only keep columns that actually exist
    cols_to_keep = [col for col in cols_to_keep if col in df.columns]
    
  
    if 'country' not in cols_to_keep:
        cols_to_keep.insert(0, 'country')
    if 'year' not in cols_to_keep:
        cols_to_keep.insert(1, 'year')
    # report what was dropped
    dropped = len(df.columns) - len(cols_to_keep)
    print(f"selected {len(cols_to_keep)} key columns (dropped {dropped} irrelevant columns)")
    
    return df[cols_to_keep]


def fill_missing(df):
    
    # count missing values before filling
    before_na = df.isnull().sum().sum()
    
    #if no missing values, skip
    if before_na == 0:
        print("no missing values to fill")
        return df
    
  
    df = df.sort_values(['country', 'year']).reset_index(drop=True)

    # forward fill within each country using previous years values
    df = df.groupby('country', group_keys=False).apply(lambda x: x.ffill()).reset_index(drop=True)
    # backward fill within each country for any remaining gaps (use next year's value)
    df = df.groupby('country', group_keys=False).apply(lambda x: x.bfill()).reset_index(drop=True)
    #count missing values after filling
    after_na = df.isnull().sum().sum()
    filled = before_na - after_na
    
    if filled > 0:
        print(f"forward/backward filled {filled:,} missing values")
    
    return df


def preprocess(df):
    
    #stages
    
    print("\npreprocessing")
    
    
    print("\ncleaning")
    df = drop_sparse_columns(df, threshold=70)
    df = filter_modern_data(df, min_year=2000)
    df = remove_duplicates(df)
    
    print("\nfeature engineering")
    df = engineer_features(df)
    
    print("\n selection")
    df = select_key_columns(df)
    
    print("\n handle missing")
    df = handle_missing(df)
    df = fill_missing(df)
    
    
    return df

# test the module
if __name__ == "__main__":
    df = pd.read_csv("data/raw/owid-energy-data.csv")
    df = preprocess(df)
    print(f"Output shape: {df.shape}")